### ISSUE TITLE
Add Share buttons to sessions

### ISSUE THREAD

**Issue by dgiormov** [dgiormov/ista.agenda.builder.web#30]

**Comment by dgiormov** [comment]
Added in session details, bottom of the page. Have problems with some buttons are visible others are not.

**Comment by panev** [comment]
The badge buttons that you've added aren't appropriate for touch screens due to their size. Not to mention they fire requests and harm performance in general. 

There's little value in letting the user know how much time a session has been shared, the tradeoff isn't really worth it. 

I'd advice adding regular social buttons, similar to those we use for the login, in a tile just saying "Share the session" or something.

**Comment by dgiormov** [comment]
Agree, the issue is that actually these social networks provide their own style and I am not sure if we can change it:(
Give me a call so we can discuss it.

**Comment by panev** [comment]
I'll add a tile with the font-awesome icons, as we discussed and reassign to you for the functionality

**Comment by panev** [comment]
I've added the new social buttons as we discussed. @dgiormov can you look into adding the functionality to them?

**Comment by dgiormov** [comment]
done
